config/routes.rb
SimonAsks::Engine.routes.draw do  

  get 'questions/tags/:tag', to: 'questions#index', as: :questions_tag
  get 'questions/show/:show', to: 'questions#index', as: :questions_list
  match 'questions/search', to: 'questions#index', as: :questions_search
  resources :questions do
    get 'mark'
    get 'edit/image', to: 'questions#edit_image'
    get 'upvote'
    get 'downvote'
    # TODO change vote methods to post
    resources :answers, controller: 'question_answers', only: [:create, :edit, :update, :destroy] do
      get 'upvote'
      get 'downvote'
      # TODO change vote methods to post
      get 'accept'
      resources :comments, controller: 'answer_comments', only: [:create, :edit, :update, :destroy]
    end
    resources :comments, controller: 'question_comments', only: [:create, :edit, :update, :destroy]
  end
  resources :comments, only: %w(create update), constraints: { format: 'js' }

  root :to => "questions#index"

end

app/models/simon_asks/ability.rb
require 'cancan'

module SimonAsks
  class Ability
    include CanCan::Ability

    # Thanks for Forem gem for the following methods
    class_attribute :abilities
    self.abilities = Set.new

    # Allows us to go beyond the standard cancan initialize method which makes it difficult for engines to
    # modify the default +Ability+ of an application.  The +ability+ argument must be a class that includes
    # the +CanCan::Ability+ module.  The registered ability should behave properly as a stand-alone class
    # and therefore should be easy to test in isolation.
    def self.register_ability(ability)
      self.abilities.add(ability)
    end

    def self.remove_ability(ability)
      self.abilities.delete(ability)
    end

    def initialize(user, params)

      if user
=begin
      # Just and Example
      # TODO do smth to automatically include it into main app
      can [:read], SimonAsks::Question
      # if user
      
        # Comments
        can [:create], SimonAsks::Comment do |c|
          if c.owner
            c.owner.respond_to?(:closed?) ? !c.owner.closed? : true
          end
        end
        can [:update], SimonAsks::Comment do |c|
          c.user_id == user.id
        end
        can [:destroy], SimonAsks::Comment do |c|
          c.user_id == user.id
        end
        # Questions
        can [:create], SimonAsks::Question
        can [:update], SimonAsks::Question do |q|
          q.user_id == user.id
        end
        can [:upvote, :downvote], SimonAsks::Question do |q|
          q.user_id != user.id
        end
        # Answers
        can [:create], SimonAsks::QuestionAnswer
        can [:update], SimonAsks::QuestionAnswer do |a|
          a.user_id == user.id
        end
        can [:upvote, :downvote], SimonAsks::QuestionAnswer do |a|
          a.user_id != user.id
        end
        # Answer comments
        can [:create], :answer_comment
        can [:destroy], :answer_comment do
          SimonAsks::Comment.find(params[:id]).user_id == user.id
        end
        # question comments
        can [:create], :question_comment
        can [:destroy], :question_comment do
          SimonAsks::Comment.find(params[:id]).user_id == user.id
        end

        if user.is? :admin
          can :manage, :all
        end
=end        

        #include any abilities registered by extensions, etc.
        Ability.abilities.each do |clazz|
          ability = clazz.send(:new, user)
          @rules = rules + ability.send(:rules)
        end

      end

    end
    
  end
end

app/models/simon_asks/rate.rb
module SimonAsks
  class Rate < ActiveRecord::Base
    belongs_to :rater, :class_name => SimonAsks.user_class
    belongs_to :rateable, :polymorphic => true
    validates_numericality_of :stars, :greater_than => 0
    
    attr_accessible :rate, :dimension
  end
end

app/controllers/simon_asks/answer_comments_controller.rb
module SimonAsks
  class AnswerCommentsController < SimonAsks::ApplicationController

    #authorize_resource class: false

    before_filter :find_question
    before_filter :find_answer, except: [:update]
    before_filter :find_comment, except: [:create]

    def create
      @comment = @answer.comments.build(params[:comment])
      @comment.user = current_user
      authorize! :create, @comment
      if @comment.save
        respond_to do |format|
          format.html { redirect_to @question, notice: t('simon_asks.comment.was.created') }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'questions/show' }
          format.js { render js: "$('.answer##{@answer.id} .add_answer_comment.loader').hide(); $('.answer##{@answer.id} .add_answer_comment_block').show();" }
        end
      end
    end

    def edit
      authorize! :edit, @comment
    end

    def update
      authorize! :update, @comment
      if @comment.update_attributes(params[:comment])
        redirect_to question_path(@question), notice: t('simon_asks.comment.was.updated')
      else
        render :edit
      end
    end

    def destroy
      authorize! :destroy, @comment
      if @comment.destroy
        respond_to do |format|
          format.html { redirect_to @question, notice: t('simon_asks.comment.was.destroyed') }
          format.js 
        end
      else
        respond_to do |format|
          format.html { redirect_to @question }
          format.js { render js: "$('.comment-item##{@comment.id}').show();" }
        end
      end
    end

    private

    def find_question
      @question = Question.find(params[:question_id])
    end

    def find_answer
      @answer = QuestionAnswer.find(params[:answer_id])
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end
  end
end

app/controllers/simon_asks/application_controller.rb
module SimonAsks
  class ApplicationController < ApplicationController
    helper SimonAsks::Engine.helpers

    check_authorization

    # simons_user

    #private

    #def current_ability
    #  @current_ability ||= SimonAsks::Ability.new(current_user, request.params)
    #end




  end
end

app/controllers/simon_asks/comments_controller.rb
module SimonAsks
  class CommentsController < SimonAsks::ApplicationController
    respond_to :js

    load_and_authorize_resource class: SimonAsks::Comment

    def create
      @comment.user = current_user
      @comment.save
      respond_with(@comment)
    end

    def update
      @comment.update_attributes(params[:comment])
      respond_with(@comment)
    end
  end
end

app/controllers/simon_asks/question_answers_controller.rb
module SimonAsks
  class QuestionAnswersController < SimonAsks::ApplicationController

    authorize_resource class: SimonAsks::QuestionAnswer

    before_filter :find_answer_by_id, only: [:edit, :update, :destroy]
    before_filter :find_answer_by_answer_id, only: [:upvote, :downvote, :accept]

    def create
      @question = Question.find(params[:question_id])

      raise CanCan::AccessDenied.new("Not authorized!", :create, SimonAsks::QuestionAnswer) if current_user.question_answers.where(:question_id => @question.id).size != 0

      @answer = QuestionAnswer.new(params[:question_answer])
      @answer.question = @question
      @answer.user = current_user

      if @answer.save
        respond_to do |format|
          format.html { redirect_to question_path(@question), notice: t('simon_asks.answer.was.created') }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'questions/show' }
          format.js { render js: "$('#add_answer.loader').hide(); $('#add_answer_block').show();" }
        end
      end
    end

    def edit
      redirect_to question_path(@answer.question) unless @answer.can_edit?(current_user)
    end

    def update
      if @answer.update_attributes(params[:question_answer])
        redirect_to question_path(@answer.question), notice: t('simon_asks.question_answer.was.updated')
      else
        render :edit
      end
    end

    def upvote
      unless current_user && @answer.user == current_user && current_user.voted_down_on?(@answer) != true
        if current_user.voted_up_on? @answer
          @answer.unvote :voter => current_user, :vote => 'like'
          @minus = 1
        else
          @answer.vote :voter => current_user, :vote => 'like'
        end
      else
        @error = 1
      end
      Opinion.calc_stat(@answer.user.userable.id) if @answer.user.medic?
    end

    def downvote
      unless current_user && @answer.user == current_user && current_user.voted_up_on?(@answer) != true
        if current_user.voted_down_on? @answer
          @answer.unvote :voter => current_user, :vote => 'bad'
          @minus = 1
        else
          @answer.vote :voter => current_user, :vote => 'bad'
        end
      else
        @error = 1
      end
      Opinion.calc_stat(@answer.user.userable.id) if @answer.user.medic?
    end

    def accept
      @check_item = false
      @uncheck_items = false
      if SimonAsks::QuestionAnswer.accepted_only.where(:question_id => @answer.question_id).size != 0
        SimonAsks::QuestionAnswer.accepted_only.where(:question_id => @answer.question_id).update_all(:accepted => false)
        @uncheck_items = true
      end  
      unless @answer.accepted    
        @answer.accepted = true
        @answer.save!
        @check_item = true
      end
    end

    def destroy
      @question = Question.find(params[:question_id])
      @answer.destroy
      redirect_to question_path(@question)
    end

    private

    def find_answer_by_id
      @answer = QuestionAnswer.find(params[:id])
    end

    def find_answer_by_answer_id
      @answer = QuestionAnswer.find(params[:answer_id])
    end
  end
end

app/controllers/simon_asks/question_comments_controller.rb
module SimonAsks
  class QuestionCommentsController < SimonAsks::ApplicationController

     #authorize_resource class: false

    before_filter :find_question
    before_filter :find_comment, except: [:create]

    def create
      @comment = @question.comments.build(params[:comment])
      @comment.user = current_user
      authorize! :create, @comment
      if @comment.save
        respond_to do |format|
          format.html { redirect_to @question, notice: t('simon_asks.comment.was.created') }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'questions/show' }
          format.js { render js: "$('#add_question_comment.loader').hide(); $('#add_question_comment_block').show();" }
        end
      end
    end

    def edit
      authorize! :edit, @comment
    end

    def update
      authorize! :update, @comment
      if @comment.update_attributes(params[:comment])
        redirect_to question_path(@question), notice: t('simon_asks.comment.was.updated')
      else
        render :edit
      end
    end

    def destroy
      authorize! :destroy, @comment
      if @comment.destroy
        respond_to do |format|
          format.html { redirect_to @question, notice: t('simon_asks.comment.was.destroyed') }
          format.js 
        end
      else
        respond_to do |format|
          format.html { redirect_to @question }
          format.js { render js: "$('.comment-item##{@comment.id}').show();" }
        end
      end
    end

    private

    def find_question
      @question = Question.find(params[:question_id])
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end
  end
end

app/controllers/simon_asks/questions_controller.rb
module SimonAsks
  class QuestionsController < SimonAsks::ApplicationController
    #include SimonAsks::QuestionsHelper

    skip_authorization_check :only => [:index, :show]
    authorize_resource class: SimonAsks::Question, except: [:index, :show]    

    before_filter :find_question_by_id, only: [:show, :edit, :update, :destroy]
    before_filter :find_question_by_question_id, only: [:mark, :edit_image, :upvote, :downvote]
    #before_filter :merge_tags, only: [:update, :create]
    before_filter :initialize_session
    before_filter :load_qa_tags
    before_filter :set_params

    #has_widgets do |root|
    #  root << widget(:ac_tags)
    #end    

    def index
      # TODO add option to enable this
      #@question_of_day = Question.find_by_marked(true)
      @questions = []

      if params[:tag]
        @questions = Question.tagged_with(params[:tag])
        @questions_size = @questions.size
      elsif params[:qa_search]
        @questions = Question.search(params)
        @questions_size = @questions.size
      elsif params[:show] || params[:sort]
        if params[:show]
          @questions = Question.sort(params[:show])
        else
          @questions = Question.sort(params[:sort], params[:direction])
        end
        @questions_size = @questions.size
      else
        @questions = Question
        @questions_size = Question.all.size
      end

      @questions = @questions.page(params[:page])
    end

    def new
      @question = Question.new
    end

    def show
      session[:simon_asks][:views]["question_#{@question.id}".to_sym] = true if @question.safely_increment_views!(session[:simon_asks])
      @related_questions = Question.related_to(@question)
      @answer = QuestionAnswer.new
    end

    def create
      @question = Question.new(params[:question])
      @question.user = current_user
      if @question.save
        redirect_to question_path(@question), notice: t('simon_asks.question.was.created')
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @question.update_attributes(params[:question])
        redirect_to question_path(@question), notice: t('simon_asks.question.was.updated')
      else
        render :edit
      end
    end

    def destroy
      @question.destroy
      redirect_to questions_path
    end

    def edit_image
    end

    def upvote
      unless current_user && @question.user == current_user && current_user.voted_down_on?(@question) != true
        if current_user.voted_up_on? @question
          @question.unvote :voter => current_user, :vote => 'like'
          @minus = 1
        else
          @question.vote :voter => current_user, :vote => 'like'
        end
      else
        @error = 1
      end
      Opinion.calc_stat(@question.user.userable.id) if @question.user.medic?
    end

    def downvote
      unless current_user && @question.user == current_user && current_user.voted_up_on?(@question) != true
        if current_user.voted_down_on? @question
          @question.unvote :voter => current_user, :vote => 'bad'
          @minus = 1
        else
          @question.vote :voter => current_user, :vote => 'bad'
        end
      else
        @error = 1
      end
      Opinion.calc_stat(@question.user.userable.id) if @question.user.medic?
    end

    private

    def set_params
      params[:direction] = 'DESC' unless params[:direction]
      params[:sort] = 'date' unless params[:sort]
    end

    def load_qa_tags
      if params[:question_tags_ids].present?
        @qa_tags = params[:question_tags_ids].split(",")
      end
    end

    def initialize_session
      session[:simon_asks] = {} unless session[:simon_asks]
      session[:simon_asks][:views] = {} unless session[:simon_asks][:views]    
    end

    def merge_tags
      if params[:question] && params[:question][:tag_list]
        params[:question][:tag_list] = params[:question][:tag_list].join(', ')
      end
    end

    def find_question_by_id
      @question = Question.find(params[:id])
    end

    def find_question_by_question_id
      @question = Question.find(params[:question_id])
    end
  end
end

app/controllers/simon_asks/tags_controller.rb
module SimonAsks
  class TagsController < SimonAsks::ApplicationController

    def index
      if params[:q].present?
        @tags = ActsAsTaggableOn::Tag.where("tags.name ILIKE ?", "%#{params[:q].downcase.to_s}%")
      else
        @tags = ActsAsTaggableOn::Tag.all
      end

      respond_to do |format|
        format.html
        format.json { render :json => @tags.collect{ |t| {:id => t.name, :name => t.name } } }
      end
    end
  end
end

app/helpers/simon_asks/application_helper.rb
module SimonAsks
  module ApplicationHelper

    def paginator collection, options = {}
      if defined?(:paginate) && collection.respond_to?(:current_page)
        paginate collection, options
      end
    end

  end
end

app/helpers/simon_asks/questions_helper.rb
module SimonAsks
  module QuestionsHelper
    def number_of_answers(question)
      question.answers_count ? question.answers_count : 0
    end

    def show_tag_list(question)
      raw question.tag_list.map { |t| link_to t, simon_asks.questions_tag_path(t), class: 'plink' }.join(', ')
    end

    def current_path
      request.env['PATH_INFO']
    end

    def show_more_questions?(user)
      true if Question.where(user_id: user).count > 3
    end

    def show_more_answers?(user)
      true if QuestionAnswer.where(user_id: user).count > 3
    end
  end
end

app/views/simon_asks/questions/_item.html.haml
- full ||= false
.question-item{ class: (full ? "full": "small")}
  .head
    .pointer
    %ul
      %li.votes
        - if full
          = render 'simon_asks/questions/vote', { question: question }
        - else
          .counter= question.score
          .label= t('simon_asks.questions.votes', count: question.score.abs)
          .pic
      %li.answers
        .counter= number_of_answers(question)
        .label
          = t('simon_asks.questions.answers', count: question.answers_count)
          .pic
      %li.views
        .counter= question.views_count
        .label
          = t('simon_asks.questions.views_simple')
          .pic
      %li.date= question.updated_at.strftime("%-d %B %Y")
  .body
    %h2.title= link_to question.title, simon_asks.question_path(question)
    .tags
      - question.tag_list.each do |tag|
        %span.tag
          = link_to tag, simon_asks.questions_tag_path(tag)
    .text
      - if full
        = @question.content_html
      - else
        = truncate(question.content, length: 180)
  .bottom
    - if full
      - if user_signed_in?
        = link_to t('simon_asks.questions.write_comment'), ".question-comments .write-comment", 'data-comment-show' => "toggle", class: 'comment'
      - if can? :update, question
        = link_to t('simon_asks.questions.edit'), edit_question_path(@question), class: 'edit'
    .author
      .avatar
        = link_to account_profile_path(question.user) do
          = image_tag user_avatar_url(question.user, true)
      .name= link_to show_user_name(question.user), account_profile_path(question.user)

- if full
  -# Comments
  .comments.question-comments
    - if user_signed_in?
      #add_question_comment.loader.hidden
        = image_tag 'ajax-loader.gif'
      #add_question_comment_block.write-comment{ style: 'display:none;' }
        .new-comment= render partial: 'simon_asks/question_comments/form', locals: { question: question }
    #question-comments-list.comments-list
      = render partial: 'simon_asks/question_comments/comment', collection: question.comments, locals: { question: question }

app/views/simon_asks/questions/_item_with_image.html.haml
.question-item.with-image
  .image= image_tag question.image.main
  .stats-wrapper
    .stats
      .votes
        %span.vote-count
          %strong= question.score
        .viewcount= t('simon_asks.questions.voutes', count: question.score)
      .answers
        %span.answer-count
          %strong= number_of_answers(question)
        .viewcount= t('simon_asks.questions.answers', count: question.answers_count)
  .summary
    %h3= link_to question.title, question
    %p= truncate(question.content, length: 300)
    .meta
      .views= t('simon_asks.questions.views', count: question.views_count)
      .tags= t('simon_asks.questions.tags') + ': ' + show_tag_list(question)
      .author= = link_to show_user_name(question.user), account_profile_path(question.user)
      .date= l question.updated_at

app/views/simon_asks/questions/_marked.html.haml
.question-marked
  %h2= t('simon_asks.questions.question_of_the_day')
  - unless question.image && question.image.blank?
    = render 'simon_asks/questions/item_with_image', question: question
  - else
    = render 'simon_asks/questions/item', question: question

app/views/simon_asks/questions/_related.html.haml
.forum-news
  %h3= t('simon_asks.questions.related_questions')
  .items
    - questions.each do |question|
      .item{ :class => cycle('', 'gray') }
        = link_to question.title, question
        .params
          = link_to show_user_name(question.user), account_profile_path(question.user) if question.user
          от
          = l question.created_at

app/views/simon_asks/questions/_sidebar.html.haml
.ask-question= link_to t('simon_asks.questions.ask'), user_signed_in? ? simon_asks.new_question_path : session_path(devise_resource_name), class: 'btn'

= form_tag(simon_asks.questions_search_path, class: "baseform searchbar") do
  .search-header= t("search.parameters")

  = hidden_field_tag :qa_search, 1

  = render 'layouts/shared_query_and_pages_filter'

  .field
    = label_tag :tags, t("search.filter.by_qa_tags")
    .tags
      = render_widget :ac_tags, :tags, collection: @qa_tags, model: 'SimonAsks::Question', data_input: { name: "question_tags_ids[]", id: "question_tags_ids" }  

  %div
    .fright
      .search-button
        %div
          %div
            = submit_tag t('find'), class: 'search-bt'
  .spacer

app/views/simon_asks/questions/_similar_questions.html.haml
.consults
  %h3
    = t('simon_asks.questions.similar_questions')
  - @related_questions.each do |question|
    .consult-item
      .title
        = link_to question.title, simon_asks.question_path(question)
      .block
        %span.date
        .col
          = question.updated_at.strftime("%-d %B %Y")
      .block
        %span.inter
        .col
          = link_to show_user_name(question.user), account_profile_path(question.user)
  -#%a{href: services_path} Все консультации 
  .spacer
  .vspace

app/views/simon_asks/questions/_vote.html.haml
= link_to question_downvote_path(question), remote: true do
  - if current_user && current_user.voted_down_on?(question)
    .cycle.blue
      .minus
  - else
    .cycle
      .minus
%span.vote-count= question.score
= link_to question_upvote_path(question), remote: true do
  - if current_user && current_user.voted_up_on?(question)
    .cycle.blue
      .plus
  - else
    .cycle
      .plus

app/views/simon_asks/questions/downvote.js.erb
$('.question .votes').html(
  "<%= escape_javascript(render partial: 'simon_asks/questions/vote', locals: {question: @question}) %>"
);

app/views/simon_asks/questions/edit.html.haml
- # Navigation
- ##############
.nav
  .location-title.fleft{ style: 'width: 400px; '}
    = link_to t('questions.show.all_questions'), questions_path
    %span= "> #{t('simon_asks.questions.edit_question')}"

- # Form
- ##############    
= render 'form'

app/views/simon_asks/questions/edit_image.html.haml
.content.title-row
  %h2= t('simon_asks.questions.edit_question')

= form_for @question do |f|
  .controls-row.big-margin.clearfix
    .btn-wrap.silver.subject
      .hint= f.label :image
      = f.file_field :image
      = f.hidden_field :image_cache
  .controls-row.big-margin.clearfix
    = f.submit t('simon_asks.questions.edit_question'), class: 'button'

app/views/simon_asks/questions/index.html.haml
#top_navigation
  .nav
    .location-title.fleft= show_proper_page_title

    .fleft.styled
      .field
        = label_tag t("search.sort.name")
        %ul.filters
          %li
            = filter_link_to 'rating', params
            = filter_arrow 'rating', params
          %li
            = filter_link_to 'date', params
            = filter_arrow 'date', params
          %li
            = filter_link_to 'views', params
            = filter_arrow 'views', params

    = render 'layouts/top_pagination', { collection: @questions, window: 5, outer_window: 2 }

- # Sidebar
- ##############
.search-bar= render 'simon_asks/questions/sidebar'

- # Right area
- ##############
.med-page-content
  .questions
  
    - if @questions.size > 0

      - @questions.each do |question|
        = render 'simon_asks/questions/item', { question: question }

    - else

      = t('search.nothing_found')

#bottom_navigation
  = render 'layouts/bottom_pagination', { collection: @questions, collection_size: @questions_size }

app/views/simon_asks/questions/new.html.haml
- # Navigation
- ##############
.nav
  .location-title.fleft{ style: 'width: 400px; '}
    = link_to t('questions.show.all_questions'), questions_path
    %span= "> #{t('simon_asks.questions.new')}"

- # Form
- ##############
= render 'form'

app/views/simon_asks/questions/show.html.haml
- # Navigation
- ##############
.nav
  .location-title.fleft{ style: 'width: 400px; '}
    = link_to t('questions.show.all_questions'), questions_path
    %span= "> #{truncate(@question.title, length: 30)}"

- # Sidebar
- ##############
.search-bar
  = render 'simon_asks/questions/sidebar'
  - if @related_questions.size > 0
    = render 'simon_asks/questions/similar_questions'

- # Right area
- ##############
.med-page-content
  .question
    = render 'simon_asks/questions/item', { question: @question, full: true }

  -# Answers
  .answers
    #answers-list
      = render partial: 'simon_asks/question_answers/answer', collection: SimonAsks::QuestionAnswer.unscoped.where(:question_id => @question.id).order('accepted desc')

    - if current_user and not @question.has_answer_by?(current_user)
      #add_answer.loader.hidden
        = image_tag 'ajax-loader.gif'
      #add_answer_block.new-answer
        %h3= t('simon_asks.questions.your_answer')
        = render partial: 'simon_asks/question_answers/form', locals: { answer: @answer, question: @question }

:javascript
  SimonAsks.preload([
    '#{asset_path('ajax-loader-mini.gif')}'
  ]);

app/views/simon_asks/questions/upvote.js.erb
$('.question .votes').html(
  "<%= escape_javascript(render partial: 'simon_asks/questions/vote', locals: {question: @question}) %>"
);