config/routes.rb
SimonAsks::Engine.routes.draw do  

  get 'questions/tags/:tag', to: 'questions#index', as: :questions_tag
  get 'questions/show/:show', to: 'questions#index', as: :questions_list
  match 'questions/search', to: 'questions#index', as: :questions_search
  resources :questions do
    get 'mark'
    get 'edit/image', to: 'questions#edit_image'
    get 'upvote'
    get 'downvote'
    # TODO change vote methods to post
    resources :answers, controller: 'question_answers', only: [:create, :edit, :update, :destroy] do
      get 'upvote'
      get 'downvote'
      # TODO change vote methods to post
      get 'accept'
      resources :comments, controller: 'answer_comments', only: [:create, :edit, :update, :destroy]
    end
    resources :comments, controller: 'question_comments', only: [:create, :edit, :update, :destroy]
  end
  resources :comments, only: %w(create update), constraints: { format: 'js' }

  root :to => "questions#index"

end

app/models/simon_asks/ability.rb
require 'cancan'

module SimonAsks
  class Ability
    include CanCan::Ability

    # Thanks for Forem gem for the following methods
    class_attribute :abilities
    self.abilities = Set.new

    # Allows us to go beyond the standard cancan initialize method which makes it difficult for engines to
    # modify the default +Ability+ of an application.  The +ability+ argument must be a class that includes
    # the +CanCan::Ability+ module.  The registered ability should behave properly as a stand-alone class
    # and therefore should be easy to test in isolation.
    def self.register_ability(ability)
      self.abilities.add(ability)
    end

    def self.remove_ability(ability)
      self.abilities.delete(ability)
    end

    def initialize(user, params)

      if user
=begin
      # Just and Example
      # TODO do smth to automatically include it into main app
      can [:read], SimonAsks::Question
      # if user
      
        # Comments
        can [:create], SimonAsks::Comment do |c|
          if c.owner
            c.owner.respond_to?(:closed?) ? !c.owner.closed? : true
          end
        end
        can [:update], SimonAsks::Comment do |c|
          c.user_id == user.id
        end
        can [:destroy], SimonAsks::Comment do |c|
          c.user_id == user.id
        end
        # Questions
        can [:create], SimonAsks::Question
        can [:update], SimonAsks::Question do |q|
          q.user_id == user.id
        end
        can [:upvote, :downvote], SimonAsks::Question do |q|
          q.user_id != user.id
        end
        # Answers
        can [:create], SimonAsks::QuestionAnswer
        can [:update], SimonAsks::QuestionAnswer do |a|
          a.user_id == user.id
        end
        can [:upvote, :downvote], SimonAsks::QuestionAnswer do |a|
          a.user_id != user.id
        end
        # Answer comments
        can [:create], :answer_comment
        can [:destroy], :answer_comment do
          SimonAsks::Comment.find(params[:id]).user_id == user.id
        end
        # question comments
        can [:create], :question_comment
        can [:destroy], :question_comment do
          SimonAsks::Comment.find(params[:id]).user_id == user.id
        end

        if user.is? :admin
          can :manage, :all
        end
=end        

        #include any abilities registered by extensions, etc.
        Ability.abilities.each do |clazz|
          ability = clazz.send(:new, user)
          @rules = rules + ability.send(:rules)
        end

      end

    end
    
  end
end

app/models/simon_asks/rate.rb
module SimonAsks
  class Rate < ActiveRecord::Base
    belongs_to :rater, :class_name => SimonAsks.user_class
    belongs_to :rateable, :polymorphic => true
    validates_numericality_of :stars, :greater_than => 0
    
    attr_accessible :rate, :dimension
  end
end

app/controllers/simon_asks/answer_comments_controller.rb
module SimonAsks
  class AnswerCommentsController < SimonAsks::ApplicationController

    #authorize_resource class: false

    before_filter :find_question
    before_filter :find_answer, except: [:update]
    before_filter :find_comment, except: [:create]

    def create
      @comment = @answer.comments.build(params[:comment])
      @comment.user = current_user
      authorize! :create, @comment
      if @comment.save
        respond_to do |format|
          format.html { redirect_to @question, notice: t('simon_asks.comment.was.created') }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'questions/show' }
          format.js { render js: "$('.answer##{@answer.id} .add_answer_comment.loader').hide(); $('.answer##{@answer.id} .add_answer_comment_block').show();" }
        end
      end
    end

    def edit
      authorize! :edit, @comment
    end

    def update
      authorize! :update, @comment
      if @comment.update_attributes(params[:comment])
        redirect_to question_path(@question), notice: t('simon_asks.comment.was.updated')
      else
        render :edit
      end
    end

    def destroy
      authorize! :destroy, @comment
      if @comment.destroy
        respond_to do |format|
          format.html { redirect_to @question, notice: t('simon_asks.comment.was.destroyed') }
          format.js 
        end
      else
        respond_to do |format|
          format.html { redirect_to @question }
          format.js { render js: "$('.comment-item##{@comment.id}').show();" }
        end
      end
    end

    private

    def find_question
      @question = Question.find(params[:question_id])
    end

    def find_answer
      @answer = QuestionAnswer.find(params[:answer_id])
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end
  end
end

app/controllers/simon_asks/application_controller.rb
module SimonAsks
  class ApplicationController < ApplicationController
    helper SimonAsks::Engine.helpers

    check_authorization

    # simons_user

    #private

    #def current_ability
    #  @current_ability ||= SimonAsks::Ability.new(current_user, request.params)
    #end




  end
end

app/controllers/simon_asks/comments_controller.rb
module SimonAsks
  class CommentsController < SimonAsks::ApplicationController
    respond_to :js

    load_and_authorize_resource class: SimonAsks::Comment

    def create
      @comment.user = current_user
      @comment.save
      respond_with(@comment)
    end

    def update
      @comment.update_attributes(params[:comment])
      respond_with(@comment)
    end
  end
end

app/controllers/simon_asks/question_answers_controller.rb
module SimonAsks
  class QuestionAnswersController < SimonAsks::ApplicationController

    authorize_resource class: SimonAsks::QuestionAnswer

    before_filter :find_answer_by_id, only: [:edit, :update, :destroy]
    before_filter :find_answer_by_answer_id, only: [:upvote, :downvote, :accept]

    def create
      @question = Question.find(params[:question_id])

      raise CanCan::AccessDenied.new("Not authorized!", :create, SimonAsks::QuestionAnswer) if current_user.question_answers.where(:question_id => @question.id).size != 0

      @answer = QuestionAnswer.new(params[:question_answer])
      @answer.question = @question
      @answer.user = current_user

      if @answer.save
        respond_to do |format|
          format.html { redirect_to question_path(@question), notice: t('simon_asks.answer.was.created') }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'questions/show' }
          format.js { render js: "$('#add_answer.loader').hide(); $('#add_answer_block').show();" }
        end
      end
    end

    def edit
      redirect_to question_path(@answer.question) unless @answer.can_edit?(current_user)
    end

    def update
      if @answer.update_attributes(params[:question_answer])
        redirect_to question_path(@answer.question), notice: t('simon_asks.question_answer.was.updated')
      else
        render :edit
      end
    end

    def upvote
      unless current_user && @answer.user == current_user && current_user.voted_down_on?(@answer) != true
        if current_user.voted_up_on? @answer
          @answer.unvote :voter => current_user, :vote => 'like'
          @minus = 1
        else
          @answer.vote :voter => current_user, :vote => 'like'
        end
      else
        @error = 1
      end
      Opinion.calc_stat(@answer.user.userable.id) if @answer.user.medic?
    end

    def downvote
      unless current_user && @answer.user == current_user && current_user.voted_up_on?(@answer) != true
        if current_user.voted_down_on? @answer
          @answer.unvote :voter => current_user, :vote => 'bad'
          @minus = 1
        else
          @answer.vote :voter => current_user, :vote => 'bad'
        end
      else
        @error = 1
      end
      Opinion.calc_stat(@answer.user.userable.id) if @answer.user.medic?
    end

    def accept
      @check_item = false
      @uncheck_items = false
      if SimonAsks::QuestionAnswer.accepted_only.where(:question_id => @answer.question_id).size != 0
        SimonAsks::QuestionAnswer.accepted_only.where(:question_id => @answer.question_id).update_all(:accepted => false)
        @uncheck_items = true
      end  
      unless @answer.accepted    
        @answer.accepted = true
        @answer.save!
        @check_item = true
      end
    end

    def destroy
      @question = Question.find(params[:question_id])
      @answer.destroy
      redirect_to question_path(@question)
    end

    private

    def find_answer_by_id
      @answer = QuestionAnswer.find(params[:id])
    end

    def find_answer_by_answer_id
      @answer = QuestionAnswer.find(params[:answer_id])
    end
  end
end

app/controllers/simon_asks/question_comments_controller.rb
module SimonAsks
  class QuestionCommentsController < SimonAsks::ApplicationController

     #authorize_resource class: false

    before_filter :find_question
    before_filter :find_comment, except: [:create]

    def create
      @comment = @question.comments.build(params[:comment])
      @comment.user = current_user
      authorize! :create, @comment
      if @comment.save
        respond_to do |format|
          format.html { redirect_to @question, notice: t('simon_asks.comment.was.created') }
          format.js
        end
      else
        respond_to do |format|
          format.html { render 'questions/show' }
          format.js { render js: "$('#add_question_comment.loader').hide(); $('#add_question_comment_block').show();" }
        end
      end
    end

    def edit
      authorize! :edit, @comment
    end

    def update
      authorize! :update, @comment
      if @comment.update_attributes(params[:comment])
        redirect_to question_path(@question), notice: t('simon_asks.comment.was.updated')
      else
        render :edit
      end
    end

    def destroy
      authorize! :destroy, @comment
      if @comment.destroy
        respond_to do |format|
          format.html { redirect_to @question, notice: t('simon_asks.comment.was.destroyed') }
          format.js 
        end
      else
        respond_to do |format|
          format.html { redirect_to @question }
          format.js { render js: "$('.comment-item##{@comment.id}').show();" }
        end
      end
    end

    private

    def find_question
      @question = Question.find(params[:question_id])
    end

    def find_comment
      @comment = Comment.find(params[:id])
    end
  end
end

app/controllers/simon_asks/questions_controller.rb
module SimonAsks
  class QuestionsController < SimonAsks::ApplicationController
    #include SimonAsks::QuestionsHelper

    skip_authorization_check :only => [:index, :show]
    authorize_resource class: SimonAsks::Question, except: [:index, :show]    

    before_filter :find_question_by_id, only: [:show, :edit, :update, :destroy]
    before_filter :find_question_by_question_id, only: [:mark, :edit_image, :upvote, :downvote]
    #before_filter :merge_tags, only: [:update, :create]
    before_filter :initialize_session
    before_filter :load_qa_tags
    before_filter :set_params

    #has_widgets do |root|
    #  root << widget(:ac_tags)
    #end    

    def index
      # TODO add option to enable this
      #@question_of_day = Question.find_by_marked(true)
      @questions = []

      if params[:tag]
        @questions = Question.tagged_with(params[:tag])
        @questions_size = @questions.size
      elsif params[:qa_search]
        @questions = Question.search(params)
        @questions_size = @questions.size
      elsif params[:show] || params[:sort]
        if params[:show]
          @questions = Question.sort(params[:show])
        else
          @questions = Question.sort(params[:sort], params[:direction])
        end
        @questions_size = @questions.size
      else
        @questions = Question
        @questions_size = Question.all.size
      end

      @questions = @questions.page(params[:page])
    end

    def new
      @question = Question.new
    end

    def show
      session[:simon_asks][:views]["question_#{@question.id}".to_sym] = true if @question.safely_increment_views!(session[:simon_asks])
      @related_questions = Question.related_to(@question)
      @answer = QuestionAnswer.new
    end

    def create
      @question = Question.new(params[:question])
      @question.user = current_user
      if @question.save
        redirect_to question_path(@question), notice: t('simon_asks.question.was.created')
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @question.update_attributes(params[:question])
        redirect_to question_path(@question), notice: t('simon_asks.question.was.updated')
      else
        render :edit
      end
    end

    def destroy
      @question.destroy
      redirect_to questions_path
    end

    def edit_image
    end

    def upvote
      unless current_user && @question.user == current_user && current_user.voted_down_on?(@question) != true
        if current_user.voted_up_on? @question
          @question.unvote :voter => current_user, :vote => 'like'
          @minus = 1
        else
          @question.vote :voter => current_user, :vote => 'like'
        end
      else
        @error = 1
      end
      Opinion.calc_stat(@question.user.userable.id) if @question.user.medic?
    end

    def downvote
      unless current_user && @question.user == current_user && current_user.voted_up_on?(@question) != true
        if current_user.voted_down_on? @question
          @question.unvote :voter => current_user, :vote => 'bad'
          @minus = 1
        else
          @question.vote :voter => current_user, :vote => 'bad'
        end
      else
        @error = 1
      end
      Opinion.calc_stat(@question.user.userable.id) if @question.user.medic?
    end

    private

    def set_params
      params[:direction] = 'DESC' unless params[:direction]
      params[:sort] = 'date' unless params[:sort]
    end

    def load_qa_tags
      if params[:question_tags_ids].present?
        @qa_tags = params[:question_tags_ids].split(",")
      end
    end

    def initialize_session
      session[:simon_asks] = {} unless session[:simon_asks]
      session[:simon_asks][:views] = {} unless session[:simon_asks][:views]    
    end

    def merge_tags
      if params[:question] && params[:question][:tag_list]
        params[:question][:tag_list] = params[:question][:tag_list].join(', ')
      end
    end

    def find_question_by_id
      @question = Question.find(params[:id])
    end

    def find_question_by_question_id
      @question = Question.find(params[:question_id])
    end
  end
end

app/controllers/simon_asks/tags_controller.rb
module SimonAsks
  class TagsController < SimonAsks::ApplicationController

    def index
      if params[:q].present?
        @tags = ActsAsTaggableOn::Tag.where("tags.name ILIKE ?", "%#{params[:q].downcase.to_s}%")
      else
        @tags = ActsAsTaggableOn::Tag.all
      end

      respond_to do |format|
        format.html
        format.json { render :json => @tags.collect{ |t| {:id => t.name, :name => t.name } } }
      end
    end
  end
end

app/helpers/simon_asks/application_helper.rb
module SimonAsks
  module ApplicationHelper

    def paginator collection, options = {}
      if defined?(:paginate) && collection.respond_to?(:current_page)
        paginate collection, options
      end
    end

  end
end

app/helpers/simon_asks/questions_helper.rb
module SimonAsks
  module QuestionsHelper
    def number_of_answers(question)
      question.answers_count ? question.answers_count : 0
    end

    def show_tag_list(question)
      raw question.tag_list.map { |t| link_to t, simon_asks.questions_tag_path(t), class: 'plink' }.join(', ')
    end

    def current_path
      request.env['PATH_INFO']
    end

    def show_more_questions?(user)
      true if Question.where(user_id: user).count > 3
    end

    def show_more_answers?(user)
      true if QuestionAnswer.where(user_id: user).count > 3
    end
  end
end

app/views/simon_asks/question_answers/_answer.html.haml
.answer-item{ id: answer.id, class: (answer.score < 0 ? "minus" : "") }
  .head
    %ul
      %li.votes= render 'simon_asks/question_answers/vote', answer: answer
      %li.accept
        - if current_user && patient? && answer.question.user_id == current_user.id  && can?(:accept, answer)
          = link_to simon_asks.question_answer_accept_path(answer.question, answer), remote: true, class: "accept_link #{answer.accepted ? 'accepted' : ''}" do
            %span.cycle
              .check
            %span.note.before= t('simon_asks.question_answers.accept')
            %span.note.after= t('simon_asks.question_answers.accepted')
      %li.date= answer.created_at.strftime("%-d %B %Y")
  .body
    .text= answer.content_html
  .bottom
    - if user_signed_in?
      = link_to t('simon_asks.questions.write_comment'), "#answer-#{answer.id} .write-comment", 'data-comment-show' => "toggle", class: 'comment'
    - if can? :update, answer
      = link_to t('simon_asks.question_answers.edit'), edit_question_answer_path(answer.question, answer), class: 'edit'
    - if can? :destroy, answer
      = link_to t('simon_asks.questions.admin.delete'), question_answer_path(answer.question, answer), :method => :delete, :confirm => "Вы уверены?", class: 'delete'
    .author
      .avatar
        = link_to account_profile_path(answer.user) do
          = image_tag user_avatar_url(answer.user)
      .name= link_to show_user_name(answer.user), account_profile_path(answer.user)

.comments.answer-comments{ id: "answer-#{answer.id}" }
  - if user_signed_in?
    .add_answer_comment.loader.hidden
      = image_tag 'ajax-loader.gif'
    .add_answer_comment_block.write-comment{ style: 'display:none;' }
      .new-comment= render partial: 'simon_asks/answer_comments/form', locals: { answer: answer }
  .answer-comments-list.comments-list
    = render partial: 'simon_asks/answer_comments/comment', collection: answer.comments, locals: { answer: answer }

app/views/simon_asks/question_answers/_form.html.haml
= form_for answer, url: question_answers_path(question), remote: true, html: {class: 'baseform'} do |f|
  = label answer, SimonAsks::QuestionAnswer.human_attribute_name(:content)
  .field= f.text_area :content
  .form-hint= t('simon_asks.questions.new_answer_hint')

  = f.submit t('simon_asks.questions.answer'), class: 'btn', id: 'answer-submit'

:javascript
  $('#answer-submit').click(function() {
    $('#add_answer_block').hide('slow');
    $('#add_answer.loader').show();
  });

app/views/simon_asks/question_answers/_list.html.haml
- answers.each do |answer|
  .answer{ :id => answer.id }
    %table
      %tr
        %td.votecell= render 'question_answers/vote', answer: answer
        %td.postcell
          .text= answer.content_html
          .meta
            .lf
              - if can? :update, answer
                = link_to t('simon_asks.answers.edit'), edit_question_answer_path(answer.question, answer)
            .rf
              .date= l answer.created_at, :full
              .author= link_to show_user_name(answer.user), account_profile_path(answer.user)
    .comments
      .comments-list= render partial: 'answer_comments/list', locals: { answer: answer }
      - if user_signed_in?
        = link_to t('simon_asks.questions.write_comment'), ".answer##{answer.id} .write-comment", 'data-comment-show' => "toggle"
        .write-comment{ style: 'display:none;' }
          .new-comment= render partial: 'answer_comments/form', locals: { answer: answer }

app/views/simon_asks/question_answers/_vote.html.haml
= link_to question_answer_downvote_path(answer.question, answer), remote: true do
  - if current_user && current_user.voted_down_on?(answer)
    .cycle.blue
      .minus
  - else
    .cycle
      .minus
%span.vote-count= answer.score
= link_to question_answer_upvote_path(answer.question, answer), remote: true do
  - if current_user && current_user.voted_up_on?(answer)
    .cycle.blue
      .plus
  - else
    .cycle
      .plus

app/views/simon_asks/question_answers/accept.js.erb
<% if @uncheck_items %>
$('.answer-item').each(function(){ $(this).find('a.accept_link').removeClass('accepted'); });
<% end %>
<% if @check_item %>
$('.answer-item').each(function(){ if($(this).attr('id') == <%= @answer.id %>){  $(this).find('a.accept_link').addClass('accepted');  } });
<% end %>

app/views/simon_asks/question_answers/create.js.erb
var context = ".answer#<%= @answer.id %>"
$('#answers-list').append("<%= j render(partial: 'answer', locals: {answer: @answer}) %>");
$('.answers > .answer-header > h3').html("<%= t('simon_asks.questions.answers_with_num', count: @answer.question.answers_count + 1) %>");
$('#add_answer.loader').hide();

SimonAsks.prepareCommentsLinks(context);
SimonAsks.prepareHints(context);

app/views/simon_asks/question_answers/downvote.js.erb
$('.answer-item#<%= @answer.id %> .votes').html(
  "<%= escape_javascript(render partial: 'simon_asks/question_answers/vote', locals: {answer: @answer}) %>"
);

app/views/simon_asks/question_answers/edit.html.haml
- # Navigation
- ##############
.nav
  .location-title.fleft{ style: 'width: 400px; '}
    = link_to t('questions.show.all_questions'), questions_path
    %span= "> #{t('simon_asks.question_answers.edit_full')}"

-#.content.title-row
  -#%h2= t('simon_asks.question_answers.edit_full')

.clearfix
= form_for @answer, html: {class: 'baseform'} do |f|
  
  - if @answer.errors.any? 
    .flash-wrapper
      .flash.error
        = t 'errors.template.header', model: t('.clinic'), count: @answer.errors.count

  = f.label :content
  .field= f.text_area :content

  .vspace
  = f.submit t('simon_asks.question_answers.edit'), class: 'btn'

app/views/simon_asks/question_answers/upvote.js.erb
$('.answer-item#<%= @answer.id %> .votes').html(
  "<%= escape_javascript(render partial: 'simon_asks/question_answers/vote', locals: {answer: @answer}) %>"
);